FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# APIBMSONDemo1

Polls is a simple API allowing consumers to view polsssssssls and vote in them.



# Company

+ name: Apiary
+ founded: 2011 (number) - The year in which the company was founded
+ address
    + stre_et: 235 Ninth Street
    + city: San Francisco
    + state: California
    + favorite: true
    + updated_at: 3059783405987
    
## Questions Collection [/questions]

### List All Questions [GET]

+ Request (application/json)
    + Attributes
        + bed_s_min: 3 (optional)
        + foundedOn: 2011
        + Test: blabla (string)
        
+ Response 200 (application/json)